# $FreeBSD$

.include <bsd.own.mk>

LIB=	llvmsoftboundcets

SRCDIR=	lib/SoftBoundCETS
SRCS=	FixByValAttributesPass.cpp \
	InstCountPass.cpp \
	InitializeSoftBound.cpp \
	SoftBoundCETS.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
